# -*- coding: utf-8 -*-
"""Iris Species Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12d4lErwiVGX0vh43xqQHun3FgjNOm7ny

#Iris Species Classification
"""

import numpy as np
import pandas as pd

data=pd.read_csv("/content/drive/MyDrive/Iris.csv")
data.head()

data.shape

data.info()

data["Species"].value_counts()

x=data.iloc[:,1:5].values
y=data.iloc[:,-1].values

from sklearn.preprocessing import LabelBinarizer

lb=LabelBinarizer()
y=lb.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.ensemble import RandomForestClassifier

classifier=RandomForestClassifier(n_estimators=100)
classifier.fit(x_train,y_train)

y_predict=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(np.argmax(y_predict,axis=1),np.argmax(y_test,axis=1))

cm

acc=accuracy_score(np.argmax(y_predict,axis=1),np.argmax(y_test,axis=1))

acc